language: minimal

services: docker

env:
    global:
        # hyphen in project names are stripped away in Travis's CI old docker-compose version
        - COMPOSE_PROJECT_NAME=elifestylecontentadapterprototype
        - IMAGE_TAG=$TRAVIS_COMMIT

install:
    - travis_retry docker-compose build

script:
    - make tests
    - .travis/smoke-test.sh

after_success:
    - .scripts/travis/push-image.sh jats-ingester

if: |
    branch = master OR \
    branch =~ /^(?:[0-9]|[1-9][0-9]*)\.(?:[0-9]|[1-9][0-9]*)$/ OR \
    tag IS present OR \
    type = pull_request
